### ISSUE TITLE
Travis can't set profiling results for pull requests

### ISSUE THREAD

**Issue by main--** [moritzuehling/demoinfo-public#25]
As seen in #23, all travis builds for pull requests currently fail.

Reason: A pull request could change **anything**, including `brofiler.py`. And **anyone** can create a pull request. Because of that, travis doesn't set secret variables when building pull requests from forks, to avoid straight up leaking the secret.

Yo @moritzuehling, please choose a solution:

 * ~~somehow convince me to fix it~~
 * Use a Workaround: Just ignore it because it doesn't affect internal pull requests and copy pull requests to internal branches to test them
 * assign it to me and I'll close it as wontfix
 * assign it to yourself and fix `brofiler.py`, so it detects pull request builds (travis will set special envvars for that) and doesn't try to set a commit status for those (just print the link to console instead)

**Comment by moritzuehling** [comment]
Meh, we don't really need this, right...?
