### ISSUE TITLE
Not an actual issue.

### ISSUE THREAD

**Issue by wsChase** [moritzuehling/demoinfo-public#30]
Hello, I'm working on my own demo parser and have a couple questions, is there a way I can contact you?

Sorry about making this an "issue", I couldn't find any other way to contact you.

**Comment by moritzuehling** [comment]
Hi!

Sorry for not answering this long! Basically everytime I'm online I'm in the [#demoinfogo channel on QuakeNet](http://webchat.quakenet.org/?channels=demoinfogo). My name there is "flai".
