### ISSUE TITLE
DevNullPlayer is broken

### ISSUE THREAD

**Issue by main--** [moritzuehling/demoinfo-public#31]
RIP travis build

https://travis-ci.org/moritzuehling/demoinfo-public/builds/48599599#L1255

```
Errors:
/home/travis/build/moritzuehling/demoinfo-public/DemoInfo.sln (default targets) ->
(Build target) ->
/home/travis/build/moritzuehling/demoinfo-public/DevNullPlayer/DevNullPlayer.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->
	Program.cs(16,12): error CS0619: `DemoInfo.DemoParser.ParseDemo(bool)' is obsolete: `Use ParserHeader() and afterwards ParseToEnd() or ParseNextTick() please'
	 26 Warning(s)
	 1 Error(s)
```

**Comment by moritzuehling** [comment]
Blah blah blah. Fixin' it.

**Comment by moritzuehling** [comment]
Tests run: 19, Errors: 0, Failures: 0, Inconclusive: 0, Time: 1.0856992 seconds

**Comment by moritzuehling** [comment]
![build passing](https://camo.githubusercontent.com/db44ee102a48baaf3cfa30cf4d00b10c9b005722/68747470733a2f2f7472617669732d63692e6f72672f6d6f7269747a7565686c696e672f64656d6f696e666f2d7075626c69632e7376673f6272616e63683d6d6173746572)
