### ISSUE TITLE
PlayerKilled event throws NullReferenceException

### ISSUE THREAD

**Issue by pawREP** [moritzuehling/demoinfo-public#32]
The title says it all. Relevant line that causes the error: 		
```	
parser.PlayerKilled += HandlePlayerKilled;
```
btw. there is also a typo in the summary of the event. "Not"->"Note"

**Comment by 0BuRner** [comment]
Could you please give a link to a demo file where it happened ? Will be easier to debug :p

**Comment by moritzuehling** [comment]
That is what I wanted to ask. I have parsed many demos and did not get the error in recent versions. 

The current build is passing meaning that at least 3 demos were parsed without any exceptions.

**Comment by moritzuehling** [comment]
[This testcase] seems to [run fine](https://gist.github.com/moritzuehling/782ec45d5a1e789981d4).

**Comment by pawREP** [comment]
Doh,I messed up. Everything works fine. Sorry for the trouble!

**Comment by moritzuehling** [comment]
No problem :)
