### ISSUE TITLE
WeaponEntityIndexOutOfRange

### ISSUE THREAD

**Issue by gocke** [moritzuehling/demoinfo-public#35]
When parsing a Demo from 04.02 an IndexOutOfRange occured in AttributeWeapon(Int32, DemoInfo.Player), with the WeaponEntityIndex being bigger than the Array of WeaponEntitites.

I can provide the Demo in question.

http://puu.sh/fyuYT/7457f89224.png

**Comment by gocke** [comment]
Demo File: http://www.file-upload.net/download-10264309/003056012444641001585_1283988829.dem.html

**Comment by moritzuehling** [comment]
Sorry, it was a dumb error. I should never use magic-numbers, ever.
